[package]
name = "wiw-boerse"
version = "0.0.1"
authors = ["Fenhl <fenhl@fenhl.net>"]

[[bin]]
name = "wiw-boerse"
path = "src/main.rs"

[dependencies]
iron = "*"
lazy_static = "*"
router = "*"
rustc-serialize = "*"

#[dependencies.static]
#git = "https://github.com/iron/static.git"
