[package]
name = "wiw-boerse"
version = "0.0.1"
authors = ["Fenhl <fenhl@fenhl.net>"]

[[bin]]
name = "wiw-boerse"
path = "src/main.rs"
doc = false
test = false
bench = false

[dependencies]
iron = "*"
lazy_static = "*"
mysql = "*"
plugin = "*"
regex = "*"
regex_macros = "*"
router = "*"
rustc-serialize = "*"

#[dependencies.static]
#git = "https://github.com/iron/static.git"

[dependencies.urlencoded]
git = "https://github.com/iron/urlencoded.git" # crates.io version is outdated
